### ISSUE TITLE
Fix interferences between tests in new unit test framework

### ISSUE THREAD

**Issue by cyrille-artho** [cyrille-artho/modbat#32]
Related to #26 #29:
It is possible that the coverage is not reset by simply calling `init`, as the original code assumed `Main.main` would be run, and all coverage data would be empty.
With two tests using the same model, executing different transitions due to different initial states or different choices taken, we can ensure that the coverage information is actually reset.

**Comment by cyrille-artho** [comment]
Some problems (see https://travis-ci.org/KotaroTanabe/modbat/builds/495336955?utm_source=github_status&utm_medium=notification ):

- Assertion failure   at modbat.mbt.MBT$.mkModel(MBT.scala:249)
- Test counts wrong:
`  [INFO] 1 tests executed, -1 ok, 2 failed.`
(failing tests are not reset to 0?)
- Five system tests fail: # count=256 ok=251 failed=5 skipped=0
  - 2 failures due to version number (tag not in forked repo?)
  - 3 tests due to new output `[DEBUG] Current InvokeTransitionQueue = ()`

**Comment by cyrille-artho** [comment]
Another assertion failure after initial partial fix:
```
  java.lang.NullPointerException:
  at modbat.cov.StateCoverage$.cover(StateCoverage.scala:8)
  at modbat.mbt.MBT.addAndLaunch(MBT.scala:446)
  at modbat.mbt.MBT$.launch(MBT.scala:298)
```

**Comment by cyrille-artho** [comment]
Now failing as follows:
```
  java.lang.NullPointerException:
  at modbat.mbt.MBT$.getMethods(MBT.scala:104)
  at modbat.mbt.MBT$.invokeAll(MBT.scala:122)
  at modbat.mbt.MBT$.invokeAnnotatedStaticMethods(MBT.scala:112)
  at modbat.mbt.Modbat$.init(Modbat.scala:76)
  at modbat.mbt.Modbat$.explore(Modbat.scala:218)
  at modbat.mbt.Main$.run(Main.scala:50)
```

**Comment by cyrille-artho** [comment]
Now works after disabling undocumented, poorly working forking in the plugin that runs scalatest unit tests in gradle.
