### ISSUE TITLE
Akka Actor not included as dependency

### ISSUE THREAD

**Issue by Phasip** [cyrille-artho/modbat#91]
After building modbat I get:

```
scala modbat.jar -v
scala modbat.jar v3.4 rev 1e055e11ef0e14274c9d410d3fa2ac89409384cf
java.lang.ClassNotFoundException: akka.actor.Scheduler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.miguno.akka.testing.VirtualTime.<init>(VirtualTime.scala:17)
	at modbat.mbt.MBT$.<init>(MBT.scala:71)
	at modbat.mbt.MBT$.<clinit>(MBT.scala)
	at modbat.mbt.Main$.setup(Main.scala:68)
	at modbat.mbt.Main$.run(Main.scala:54)
	at modbat.mbt.Main$.main(Main.scala:13)
	at modbat.mbt.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.JarRunner$.run(MainGenericRunner.scala:13)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.JarRunner$.runJar(MainGenericRunner.scala:25)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:69)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

It seems like the akka actor is not included in the built modbat jar.
Downloading akka actor manually and setting classpath is a workaround.

```
# wget https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.5.19/akka-
# CLASSPATH=akka-actor_2.11-2.5.19.jar scala modbat.jar -v
scala modbat.jar v3.4 rev 1e055e11ef0e14274c9d410d3fa2ac89409384cf
```

Git revision:
```
git log -1
commit 1e055e11ef0e14274c9d410d3fa2ac89409384cf (HEAD -> master, origin/master, origin/HEAD)
Author: cyrille-artho <cyrille-artho@users.noreply.github.com>
Date:   Thu Feb 20 14:40:05 2020 +0100

    Update README.md

```

**Comment by cyrille-artho** [comment]
Dear Phasip,
Thank you very much for tracking this down. We have also noticed that some versions of Scala do not include that library (anymore), and depending on the system's configuration, it is not found.

If you can provide a patch for `build.gradle`, I will gladly include it.
